# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: team@fornax
author_name: Fornax Team
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend
labextension_name: fornax-labextension
project_short_description: A JupyterLab extension for Fornax
python_name: fornax_labextension
repository: ''
test: true

