name: Release

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to upload release assets

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install dependencies
      run: |
        python -m pip install -U "jupyterlab>=4.0.0,<5"
        python -m pip install build

    - name: Build the extension
      run: |
        set -eux
        
        # Install the extension in development mode
        python -m pip install -e .[test]
        
        # Verify the extension is installed
        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "fornax-labextension.*OK"

    - name: Build packages
      run: |
        set -eux
        
        # Build both wheel and source distribution
        python -m build
        
        # List the built packages
        ls -la dist/

    - name: Verify packages
      run: |
        set -eux
        
        # Test installation from wheel
        pip install --force-reinstall dist/*.whl
        
        # Verify the extension still works
        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "fornax-labextension.*OK"
        python -m jupyterlab.browser_check --no-browser-test

    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*.whl
          dist/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to PyPI (optional)
      # Uncomment and configure if you want to publish to PyPI
      # You'll need to add PYPI_API_TOKEN to your repository secrets
      if: false  # Change to true when ready to publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
